# Generated by Django 4.0.4 on 2022-05-02 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StarInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StarInventory.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('cost', models.FloatField()),
                ('reorder_level', models.IntegerField(default=0)),
                ('order_quantity', models.IntegerField(default=20)),
                ('reserved_stock', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=100)),
                ('manufacturer', models.CharField(max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StarInventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StarInventory.part')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StarInventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('customerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StarInventory.customerorder')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StarInventory.part')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='part',
            field=models.ManyToManyField(through='StarInventory.OrderItem', to='StarInventory.part'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('part', 'customerOrder'), name='once_per_customerOrder_part'),
        ),
    ]
