# Generated by Django 4.0.4 on 2022-05-08 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StarInventory', '0002_customerorder_part_supplierorder_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='customerorder',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customerOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='StarInventory.customerorder'),
        ),
        migrations.AlterField(
            model_name='part',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
