# Generated by Django 4.0.4 on 2022-05-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarInventory', '0003_alter_customerorder_options_customerorder_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
    ]
