# Generated by Django 4.0.4 on 2022-05-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarInventory', '0005_customerorder_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
