# Generated by Django 4.0.4 on 2022-05-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarInventory', '0007_part_manufacturer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='manufacturer_number',
            field=models.CharField(max_length=20),
        ),
    ]
