# Generated by Django 4.0.4 on 2022-05-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StarInventory', '0009_alter_part_manufacturer_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierorder',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='supplierorder',
            old_name='total_price',
            new_name='value',
        ),
        migrations.AddField(
            model_name='part',
            name='item_in_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StarInventory.part')),
                ('supplierOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order_items', to='StarInventory.supplierorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplierorderitem',
            constraint=models.UniqueConstraint(fields=('part', 'supplierOrder'), name='once_per_supplierOrder_part'),
        ),
    ]
