# Generated by Django 4.0.4 on 2022-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarInventory', '0010_alter_supplierorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='part',
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='part',
            field=models.ManyToManyField(through='StarInventory.SupplierOrderItem', to='StarInventory.part'),
        ),
    ]
